version: "3.8"
services:
  web:
    build: ./
    ports:
      - "3000:3000" 
    depends_on:
      - db 
    environment:
      - DB_HOST=db 
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_DATABASE=mydb

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword 
  
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql 
      - db_data:/var/lib/mysql 

volumes:
  db_data:
